// Code generated by counterfeiter. DO NOT EDIT.
// with command: counterfeiter -p -o /Users/hjortj1/go/src/code.cloudfoundry.org/goshims/syscallshim syscall
package syscallshim

//go:generate counterfeiter -o syscall_fake/fake_syscall.go . Syscall
type Syscall interface {
	BpfStmt(code, k int) *syscall.BpfInsn
	BpfJump(code, k, jt, jf int) *syscall.BpfInsn
	BpfBuflen(fd int) (int, error)
	SetBpfBuflen(fd, l int) (int, error)
	BpfDatalink(fd int) (int, error)
	SetBpfDatalink(fd, t int) (int, error)
	SetBpfPromisc(fd, m int) error
	FlushBpf(fd int) error
	BpfInterface(fd int, name string) (string, error)
	SetBpfInterface(fd int, name string) error
	BpfTimeout(fd int) (*syscall.Timeval, error)
	SetBpfTimeout(fd int, tv *syscall.Timeval) error
	BpfStats(fd int) (*syscall.BpfStat, error)
	SetBpfImmediate(fd, m int) error
	SetBpf(fd int, i []syscall.BpfInsn) error
	CheckBpfVersion(fd int) error
	BpfHeadercmpl(fd int) (int, error)
	SetBpfHeadercmpl(fd, f int) error
	UnmarshalDir(b []byte) (*syscall.Dir, error)
	ParseDirent(buf []byte, max int, names []string) (consumed int, count int, newnames []string)
	Syscall(trap, nargs, a1, a2, a3 uintptr) (r1, r2 uintptr, err syscall.Errno)
	Syscall6(trap, nargs, a1, a2, a3, a4, a5, a6 uintptr) (r1, r2 uintptr, err syscall.Errno)
	Syscall9(trap, nargs, a1, a2, a3, a4, a5, a6, a7, a8, a9 uintptr) (r1, r2 uintptr, err syscall.Errno)
	Syscall12(trap, nargs, a1, a2, a3, a4, a5, a6, a7, a8, a9, a10, a11, a12 uintptr) (r1, r2 uintptr, err syscall.Errno)
	Syscall15(trap, nargs, a1, a2, a3, a4, a5, a6, a7, a8, a9, a10, a11, a12, a13, a14, a15 uintptr) (r1, r2 uintptr, err syscall.Errno)
	LoadDLL(name string) (*syscall.DLL, error)
	MustLoadDLL(name string) *syscall.DLL
	NewLazyDLL(name string) *syscall.LazyDLL
	Getenv(key string) (value string, found bool)
	Setenv(key, value string) error
	Clearenv()
	Unsetenv(key string) error
	Environ() []string
	StringSlicePtr(ss []string) []*byte
	SlicePtrFromStrings(ss []string) ([]*byte, error)
	ForkExec(argv0 string, argv []string, attr *syscall.ProcAttr) (pid int, err error)
	StartProcess(argv0 string, argv []string, attr *syscall.ProcAttr) (pid int, handle uintptr, err error)
	Exec(argv0 string, argv []string, envv []string) (err error)
	WaitProcess(pid int, w *syscall.Waitmsg) (err error)
	CloseOnExec(fd int)
	SetNonblock(fd int, nonblocking bool) (err error)
	EscapeArg(s string) string
	FullPath(name string) (path string, err error)
	Close(fd int) error
	Dup(fd int) (int, error)
	Dup2(fd, newfd int) error
	Fstat(fd int, st *syscall.Stat_t) error
	Read(fd int, b []byte) (int, error)
	Write(fd int, b []byte) (int, error)
	Pread(fd int, b []byte, offset int64) (int, error)
	Pwrite(fd int, b []byte, offset int64) (int, error)
	Seek(fd int, offset int64, whence int) (int64, error)
	Pipe(fd []int) error
	FcntlFlock(fd uintptr, cmd int, lk *syscall.Flock_t) error
	ReadDirent(fd int, buf []byte) (int, error)
	Open(path string, openmode int, perm uint32) (fd int, err error)
	Mkdir(path string, perm uint32) error
	Getcwd(buf []byte) (n int, err error)
	Stat(path string, st *syscall.Stat_t) error
	Lstat(path string, st *syscall.Stat_t) error
	Unlink(path string) error
	Rmdir(path string) error
	Chmod(path string, mode uint32) error
	Fchmod(fd int, mode uint32) error
	Chown(path string, uid, gid int) error
	Fchown(fd int, uid, gid int) error
	Lchown(path string, uid, gid int) error
	UtimesNano(path string, ts []syscall.Timespec) error
	Link(path, link string) error
	Rename(from, to string) error
	Truncate(path string, length int64) error
	Ftruncate(fd int, length int64) error
	Chdir(path string) error
	Fchdir(fd int) error
	Readlink(path string, buf []byte) (n int, err error)
	Symlink(path, link string) error
	Fsync(fd int) error
	LsfStmt(code, k int) *syscall.SockFilter
	LsfJump(code, k, jt, jf int) *syscall.SockFilter
	LsfSocket(ifindex, proto int) (int, error)
	SetLsfPromisc(name string, m bool) error
	AttachLsf(fd int, i []syscall.SockFilter) error
	DetachLsf(fd int) error
	ParseFiles(fs []string) (*Source, error)
	Socket(proto, sotype, unused int) (fd int, err error)
	Bind(fd int, sa syscall.Sockaddr) error
	StopIO(fd int) error
	Listen(fd int, backlog int) error
	Accept(fd int) (newfd int, sa syscall.Sockaddr, err error)
	Getsockname(fd int) (sa syscall.Sockaddr, err error)
	Getpeername(fd int) (sa syscall.Sockaddr, err error)
	Connect(fd int, sa syscall.Sockaddr) error
	Recvfrom(fd int, p []byte, flags int) (n int, from syscall.Sockaddr, err error)
	Sendto(fd int, p []byte, flags int, to syscall.Sockaddr) error
	Recvmsg(fd int, p, oob []byte, flags int) (n, oobn, recvflags int, from syscall.Sockaddr, err error)
	Sendmsg(fd int, p, oob []byte, to syscall.Sockaddr, flags int) error
	SendmsgN(fd int, p, oob []byte, to syscall.Sockaddr, flags int) (n int, err error)
	GetsockoptInt(fd, level, opt int) (value int, err error)
	SetsockoptInt(fd, level, opt int, value int) error
	SetsockoptByte(fd, level, opt int, value byte) error
	SetsockoptLinger(fd, level, opt int, l *syscall.Linger) error
	SetReadDeadline(fd int, t int64) error
	SetWriteDeadline(fd int, t int64) error
	Shutdown(fd int, how int) error
	SetsockoptICMPv6Filter(fd, level, opt int, filter *syscall.ICMPv6Filter) error
	SetsockoptIPMreq(fd, level, opt int, mreq *syscall.IPMreq) error
	SetsockoptIPv6Mreq(fd, level, opt int, mreq *syscall.IPv6Mreq) error
	SetsockoptInet4Addr(fd, level, opt int, value [4]byte) error
	SetsockoptString(fd, level, opt int, s string) error
	SetsockoptTimeval(fd, level, opt int, tv *syscall.Timeval) error
	Socketpair(domain, typ, proto int) (fd [2]int, err error)
	NetlinkRIB(proto, family int) ([]byte, error)
	ParseNetlinkMessage(b []byte) ([]syscall.NetlinkMessage, error)
	ParseNetlinkRouteAttr(m *syscall.NetlinkMessage) ([]syscall.NetlinkRouteAttr, error)
	Fixwd()
	Getwd() (wd string, err error)
	RouteRIB(facility, param int) ([]byte, error)
	ParseRoutingMessage(b []byte) (msgs []syscall.RoutingMessage, err error)
	ParseRoutingSockaddr(msg syscall.RoutingMessage) ([]syscall.Sockaddr, error)
	TranslateAccountName(username string, from, to uint32, initSize int) (string, error)
	StringToSid(s string) (*syscall.SID, error)
	LookupSID(system, account string) (sid *syscall.SID, domain string, accType uint32, err error)
	OpenCurrentProcessToken() (syscall.Token, error)
	UnixCredentials(ucred *syscall.Ucred) []byte
	ParseUnixCredentials(m *syscall.SocketControlMessage) (*syscall.Ucred, error)
	CmsgLen(datalen int) int
	CmsgSpace(datalen int) int
	ParseSocketControlMessage(b []byte) ([]syscall.SocketControlMessage, error)
	UnixRights(fds ...int) []byte
	ParseUnixRights(m *syscall.SocketControlMessage) ([]int, error)
	StringByteSlice(s string) []byte
	ByteSliceFromString(s string) ([]byte, error)
	StringBytePtr(s string) *byte
	BytePtrFromString(s string) (*byte, error)
	Getpagesize() int
	Getgroups() (gids []int, err error)
	Setgroups(gids []int) (err error)
	Wait4(pid int, wstatus *syscall.WaitStatus, options int, rusage *syscall.Rusage) (wpid int, err error)
	GetsockoptByte(fd, level, opt int) (value byte, err error)
	GetsockoptInet4Addr(fd, level, opt int) (value [4]byte, err error)
	GetsockoptIPMreq(fd, level, opt int) (*syscall.IPMreq, error)
	GetsockoptIPv6Mreq(fd, level, opt int) (*syscall.IPv6Mreq, error)
	GetsockoptIPv6MTUInfo(fd, level, opt int) (*syscall.IPv6MTUInfo, error)
	GetsockoptICMPv6Filter(fd, level, opt int) (*syscall.ICMPv6Filter, error)
	Kevent(kq int, changes, events []syscall.Kevent_t, timeout *syscall.Timespec) (n int, err error)
	Sysctl(name string) (value string, err error)
	SysctlUint32(name string) (value uint32, err error)
	Utimes(path string, tv []syscall.Timeval) (err error)
	Futimes(fd int, tv []syscall.Timeval) (err error)
	Mmap(fd int, offset int64, length int, prot int, flags int) (data []byte, err error)
	Munmap(b []byte) (err error)
	PtraceAttach(pid int) (err error)
	PtraceDetach(pid int) (err error)
	Getfsstat(buf []syscall.Statfs_t, flags int) (n int, err error)
	Kill(pid int, signum syscall.Signal) (err error)
	Gettimeofday(tv *syscall.Timeval) error
	SetKevent(k *syscall.Kevent_t, fd, mode, flags int)
	GetsockoptIPMreqn(fd, level, opt int) (*syscall.IPMreqn, error)
	SetsockoptIPMreqn(fd, level, opt int, mreq *syscall.IPMreqn) (err error)
	Accept4(fd, flags int) (nfd int, sa syscall.Sockaddr, err error)
	Access(path string, mode uint32) (err error)
	Creat(path string, mode uint32) (fd int, err error)
	Mknod(path string, mode uint32, dev int) (err error)
	Openat(dirfd int, path string, flags int, mode uint32) (fd int, err error)
	Unlinkat(dirfd int, path string) error
	Futimesat(dirfd int, path string, tv []syscall.Timeval) (err error)
	Mkfifo(path string, mode uint32) (err error)
	GetsockoptUcred(fd, level, opt int) (*syscall.Ucred, error)
	BindToDevice(fd int, device string) (err error)
	PtracePeekText(pid int, addr uintptr, out []byte) (count int, err error)
	PtracePeekData(pid int, addr uintptr, out []byte) (count int, err error)
	PtracePokeText(pid int, addr uintptr, data []byte) (count int, err error)
	PtracePokeData(pid int, addr uintptr, data []byte) (count int, err error)
	PtraceGetRegs(pid int, regsout *syscall.PtraceRegs) (err error)
	PtraceSetRegs(pid int, regs *syscall.PtraceRegs) (err error)
	PtraceSetOptions(pid int, options int) (err error)
	PtraceGetEventMsg(pid int) (msg uint, err error)
	PtraceCont(pid int, signal int) (err error)
	PtraceSyscall(pid int, signal int) (err error)
	PtraceSingleStep(pid int) (err error)
	Reboot(cmd int) (err error)
	Mount(source string, target string, fstype string, flags uintptr, data string) (err error)
	Getpgrp() (pid int)
	Setuid(uid int) (err error)
	Setgid(gid int) (err error)
	Pipe2(p []int, flags int) (err error)
	Getrlimit(resource int, rlim *syscall.Rlimit) (err error)
	Setrlimit(resource int, rlim *syscall.Rlimit) (err error)
	Fstatfs(fd int, buf *syscall.Statfs_t) (err error)
	Statfs(path string, buf *syscall.Statfs_t) (err error)
	Time(t *syscall.Time_t) (tt syscall.Time_t, err error)
	InotifyInit() (fd int, err error)
	Ioperm(from int, num int, on int) (err error)
	Iopl(level int) (err error)
	RawSyscall(trap, a1, a2, a3 uintptr) (r1, r2 uintptr, err syscall.Errno)
	RawSyscall6(trap, a1, a2, a3, a4, a5, a6 uintptr) (r1, r2 uintptr, err syscall.Errno)
	Getegid() int
	Geteuid() int
	Getgid() int
	Getppid() int
	Getpid() int
	Getuid() int
	Sendfile(outfd int, infd int, offset *int64, count int) (written int, err error)
	Getdirentries(fd int, buf []byte, basep *uintptr) (n int, err error)
	NewError(s string) error
	Exit(code int)
	Fd2path(fd int) (path string, err error)
	Await(w *syscall.Waitmsg) (err error)
	Unmount(name, old string) (err error)
	NsecToTimeval(nsec int64) (tv syscall.Timeval)
	Create(path string, mode int, perm uint32) (fd int, err error)
	Remove(path string) error
	Wstat(path string, edir []byte) (err error)
	Gethostname() (name string, err error)
	Getexecname() (path string, err error)
	StringToUTF16(s string) []uint16
	UTF16FromString(s string) ([]uint16, error)
	UTF16ToString(s []uint16) string
	StringToUTF16Ptr(s string) *uint16
	UTF16PtrFromString(s string) (*uint16, error)
	FormatMessage(flags uint32, msgsrc uint32, msgid uint32, langid uint32, buf []uint16, args *byte) (n uint32, err error)
	NewCallback(fn interface{}) uintptr
	NewCallbackCDecl(fn interface{}) uintptr
	ComputerName() (name string, err error)
	LoadCancelIoEx() error
	LoadSetFileCompletionNotificationModes() error
	WSASendto(s syscall.Handle, bufs *syscall.WSABuf, bufcnt uint32, sent *uint32, flags uint32, to syscall.Sockaddr, overlapped *syscall.Overlapped, croutine *byte) (err error)
	LoadGetAddrInfo() error
	LoadConnectEx() error
	ConnectEx(fd syscall.Handle, sa syscall.Sockaddr, sendBuf *byte, sendDataLen uint32, bytesSent *uint32, overlapped *syscall.Overlapped) error
	TimespecToNsec(ts syscall.Timespec) int64
	NsecToTimespec(nsec int64) (ts syscall.Timespec)
	FindFirstFile(name *uint16, data *syscall.Win32finddata) (handle syscall.Handle, err error)
	FindNextFile(handle syscall.Handle, data *syscall.Win32finddata) (err error)
	LoadCreateSymbolicLink() error
	TimevalToNsec(tv syscall.Timeval) int64
	Adjtime(delta *syscall.Timeval, olddelta *syscall.Timeval) (err error)
	Chflags(path string, flags int) (err error)
	Chroot(path string) (err error)
	Exchangedata(path1 string, path2 string, options int) (err error)
	Fchflags(fd int, flags int) (err error)
	Flock(fd int, how int) (err error)
	Fpathconf(fd int, name int) (val int, err error)
	Getdtablesize() (size int)
	Getpgid(pid int) (pgid int, err error)
	Getpriority(which int, who int) (prio int, err error)
	Getrusage(who int, rusage *syscall.Rusage) (err error)
	Getsid(pid int) (sid int, err error)
	Issetugid() (tainted bool)
	Kqueue() (fd int, err error)
	Mlock(b []byte) (err error)
	Mlockall(flags int) (err error)
	Mprotect(b []byte, prot int) (err error)
	Munlock(b []byte) (err error)
	Munlockall() (err error)
	Pathconf(path string, name int) (val int, err error)
	Revoke(path string) (err error)
	Select(n int, r *syscall.FdSet, w *syscall.FdSet, e *syscall.FdSet, timeout *syscall.Timeval) (err error)
	Setegid(egid int) (err error)
	Seteuid(euid int) (err error)
	Setlogin(name string) (err error)
	Setpgid(pid int, pgid int) (err error)
	Setpriority(which int, who int, prio int) (err error)
	Setprivexec(flag int) (err error)
	Setregid(rgid int, egid int) (err error)
	Setreuid(ruid int, euid int) (err error)
	Setsid() (pid int, err error)
	Settimeofday(tp *syscall.Timeval) (err error)
	Sync() (err error)
	Umask(newmask int) (oldmask int)
	Undelete(path string) (err error)
	Nanosleep(time *syscall.Timespec, leftover *syscall.Timespec) (err error)
	Acct(path string) (err error)
	Adjtimex(buf *syscall.Timex) (state int, err error)
	Dup3(oldfd int, newfd int, flags int) (err error)
	EpollCreate(size int) (fd int, err error)
	EpollCreate1(flag int) (fd int, err error)
	EpollCtl(epfd int, op int, fd int, event *syscall.EpollEvent) (err error)
	EpollWait(epfd int, events []syscall.EpollEvent, msec int) (n int, err error)
	Faccessat(dirfd int, path string, mode uint32, flags int) (err error)
	Fallocate(fd int, mode uint32, off int64, len int64) (err error)
	Fchmodat(dirfd int, path string, mode uint32, flags int) (err error)
	Fchownat(dirfd int, path string, uid int, gid int, flags int) (err error)
	Fdatasync(fd int) (err error)
	Getdents(fd int, buf []byte) (n int, err error)
	Gettid() (tid int)
	Getxattr(path string, attr string, dest []byte) (sz int, err error)
	InotifyAddWatch(fd int, pathname string, mask uint32) (watchdesc int, err error)
	InotifyInit1(flags int) (fd int, err error)
	InotifyRmWatch(fd int, watchdesc uint32) (success int, err error)
	Klogctl(typ int, buf []byte) (n int, err error)
	Listxattr(path string, dest []byte) (sz int, err error)
	Mkdirat(dirfd int, path string, mode uint32) (err error)
	Mknodat(dirfd int, path string, mode uint32, dev int) (err error)
	Pause() (err error)
	PivotRoot(newroot string, putold string) (err error)
	Removexattr(path string, attr string) (err error)
	Renameat(olddirfd int, oldpath string, newdirfd int, newpath string) (err error)
	Setdomainname(p []byte) (err error)
	Sethostname(p []byte) (err error)
	Setxattr(path string, attr string, data []byte, flags int) (err error)
	Sysinfo(info *syscall.Sysinfo_t) (err error)
	Tee(rfd int, wfd int, len int, flags int) (n int64, err error)
	Tgkill(tgid int, tid int, sig syscall.Signal) (err error)
	Times(tms *syscall.Tms) (ticks uintptr, err error)
	Uname(buf *syscall.Utsname) (err error)
	Unshare(flags int) (err error)
	Ustat(dev int, ubuf *syscall.Ustat_t) (err error)
	Utime(path string, buf *syscall.Utimbuf) (err error)
	Madvise(b []byte, advice int) (err error)
	Setfsgid(gid int) (err error)
	Setfsuid(uid int) (err error)
	Setresgid(rgid int, egid int, sgid int) (err error)
	Setresuid(ruid int, euid int, suid int) (err error)
	Splice(rfd int, roff *int64, wfd int, woff *int64, len int, flags int) (n int, err error)
	SyncFileRange(fd int, off int64, n int64, flags int) (err error)
	Fstatat(fd int, path string, stat *syscall.Stat_t, flags int) (err error)
	Fwstat(fd int, edir []byte) (err error)
	GetLastError() (lasterr error)
	LoadLibrary(libname string) (handle syscall.Handle, err error)
	FreeLibrary(handle syscall.Handle) (err error)
	GetProcAddress(module syscall.Handle, procname string) (proc uintptr, err error)
	GetVersion() (ver uint32, err error)
	ExitProcess(exitcode uint32)
	CreateFile(name *uint16, access uint32, mode uint32, sa *syscall.SecurityAttributes, createmode uint32, attrs uint32, templatefile int32) (handle syscall.Handle, err error)
	ReadFile(handle syscall.Handle, buf []byte, done *uint32, overlapped *syscall.Overlapped) (err error)
	WriteFile(handle syscall.Handle, buf []byte, done *uint32, overlapped *syscall.Overlapped) (err error)
	SetFilePointer(handle syscall.Handle, lowoffset int32, highoffsetptr *int32, whence uint32) (newlowoffset uint32, err error)
	CloseHandle(handle syscall.Handle) (err error)
	GetStdHandle(stdhandle int) (handle syscall.Handle, err error)
	FindClose(handle syscall.Handle) (err error)
	GetFileInformationByHandle(handle syscall.Handle, data *syscall.ByHandleFileInformation) (err error)
	GetCurrentDirectory(buflen uint32, buf *uint16) (n uint32, err error)
	SetCurrentDirectory(path *uint16) (err error)
	CreateDirectory(path *uint16, sa *syscall.SecurityAttributes) (err error)
	RemoveDirectory(path *uint16) (err error)
	DeleteFile(path *uint16) (err error)
	MoveFile(from *uint16, to *uint16) (err error)
	GetComputerName(buf *uint16, n *uint32) (err error)
	SetEndOfFile(handle syscall.Handle) (err error)
	GetSystemTimeAsFileTime(time *syscall.Filetime)
	GetTimeZoneInformation(tzi *syscall.Timezoneinformation) (rc uint32, err error)
	CreateIoCompletionPort(filehandle syscall.Handle, cphandle syscall.Handle, key uint32, threadcnt uint32) (handle syscall.Handle, err error)
	GetQueuedCompletionStatus(cphandle syscall.Handle, qty *uint32, key *uint32, overlapped **syscall.Overlapped, timeout uint32) (err error)
	PostQueuedCompletionStatus(cphandle syscall.Handle, qty uint32, key uint32, overlapped *syscall.Overlapped) (err error)
	CancelIo(s syscall.Handle) (err error)
	CancelIoEx(s syscall.Handle, o *syscall.Overlapped) (err error)
	CreateProcess(appName *uint16, commandLine *uint16, procSecurity *syscall.SecurityAttributes, threadSecurity *syscall.SecurityAttributes, inheritHandles bool, creationFlags uint32, env *uint16, currentDir *uint16, startupInfo *syscall.StartupInfo, outProcInfo *syscall.ProcessInformation) (err error)
	OpenProcess(da uint32, inheritHandle bool, pid uint32) (handle syscall.Handle, err error)
	TerminateProcess(handle syscall.Handle, exitcode uint32) (err error)
	GetExitCodeProcess(handle syscall.Handle, exitcode *uint32) (err error)
	GetStartupInfo(startupInfo *syscall.StartupInfo) (err error)
	GetCurrentProcess() (pseudoHandle syscall.Handle, err error)
	GetProcessTimes(handle syscall.Handle, creationTime *syscall.Filetime, exitTime *syscall.Filetime, kernelTime *syscall.Filetime, userTime *syscall.Filetime) (err error)
	DuplicateHandle(hSourceProcessHandle syscall.Handle, hSourceHandle syscall.Handle, hTargetProcessHandle syscall.Handle, lpTargetHandle *syscall.Handle, dwDesiredAccess uint32, bInheritHandle bool, dwOptions uint32) (err error)
	WaitForSingleObject(handle syscall.Handle, waitMilliseconds uint32) (event uint32, err error)
	GetTempPath(buflen uint32, buf *uint16) (n uint32, err error)
	CreatePipe(readhandle *syscall.Handle, writehandle *syscall.Handle, sa *syscall.SecurityAttributes, size uint32) (err error)
	GetFileType(filehandle syscall.Handle) (n uint32, err error)
	CryptAcquireContext(provhandle *syscall.Handle, container *uint16, provider *uint16, provtype uint32, flags uint32) (err error)
	CryptReleaseContext(provhandle syscall.Handle, flags uint32) (err error)
	CryptGenRandom(provhandle syscall.Handle, buflen uint32, buf *byte) (err error)
	GetEnvironmentStrings() (envs *uint16, err error)
	FreeEnvironmentStrings(envs *uint16) (err error)
	GetEnvironmentVariable(name *uint16, buffer *uint16, size uint32) (n uint32, err error)
	SetEnvironmentVariable(name *uint16, value *uint16) (err error)
	SetFileTime(handle syscall.Handle, ctime *syscall.Filetime, atime *syscall.Filetime, wtime *syscall.Filetime) (err error)
	GetFileAttributes(name *uint16) (attrs uint32, err error)
	SetFileAttributes(name *uint16, attrs uint32) (err error)
	GetFileAttributesEx(name *uint16, level uint32, info *byte) (err error)
	GetCommandLine() (cmd *uint16)
	CommandLineToArgv(cmd *uint16, argc *int32) (argv *[8192]*[8192]uint16, err error)
	LocalFree(hmem syscall.Handle) (handle syscall.Handle, err error)
	SetHandleInformation(handle syscall.Handle, mask uint32, flags uint32) (err error)
	FlushFileBuffers(handle syscall.Handle) (err error)
	GetFullPathName(path *uint16, buflen uint32, buf *uint16, fname **uint16) (n uint32, err error)
	GetLongPathName(path *uint16, buf *uint16, buflen uint32) (n uint32, err error)
	GetShortPathName(longpath *uint16, shortpath *uint16, buflen uint32) (n uint32, err error)
	CreateFileMapping(fhandle syscall.Handle, sa *syscall.SecurityAttributes, prot uint32, maxSizeHigh uint32, maxSizeLow uint32, name *uint16) (handle syscall.Handle, err error)
	MapViewOfFile(handle syscall.Handle, access uint32, offsetHigh uint32, offsetLow uint32, length uintptr) (addr uintptr, err error)
	UnmapViewOfFile(addr uintptr) (err error)
	FlushViewOfFile(addr uintptr, length uintptr) (err error)
	VirtualLock(addr uintptr, length uintptr) (err error)
	VirtualUnlock(addr uintptr, length uintptr) (err error)
	TransmitFile(s syscall.Handle, handle syscall.Handle, bytesToWrite uint32, bytsPerSend uint32, overlapped *syscall.Overlapped, transmitFileBuf *syscall.TransmitFileBuffers, flags uint32) (err error)
	ReadDirectoryChanges(handle syscall.Handle, buf *byte, buflen uint32, watchSubTree bool, mask uint32, retlen *uint32, overlapped *syscall.Overlapped, completionRoutine uintptr) (err error)
	CertOpenSystemStore(hprov syscall.Handle, name *uint16) (store syscall.Handle, err error)
	CertOpenStore(storeProvider uintptr, msgAndCertEncodingType uint32, cryptProv uintptr, flags uint32, para uintptr) (handle syscall.Handle, err error)
	CertEnumCertificatesInStore(store syscall.Handle, prevContext *syscall.CertContext) (context *syscall.CertContext, err error)
	CertAddCertificateContextToStore(store syscall.Handle, certContext *syscall.CertContext, addDisposition uint32, storeContext **syscall.CertContext) (err error)
	CertCloseStore(store syscall.Handle, flags uint32) (err error)
	CertGetCertificateChain(engine syscall.Handle, leaf *syscall.CertContext, time *syscall.Filetime, additionalStore syscall.Handle, para *syscall.CertChainPara, flags uint32, reserved uintptr, chainCtx **syscall.CertChainContext) (err error)
	CertFreeCertificateChain(ctx *syscall.CertChainContext)
	CertCreateCertificateContext(certEncodingType uint32, certEncoded *byte, encodedLen uint32) (context *syscall.CertContext, err error)
	CertFreeCertificateContext(ctx *syscall.CertContext) (err error)
	CertVerifyCertificateChainPolicy(policyOID uintptr, chain *syscall.CertChainContext, para *syscall.CertChainPolicyPara, status *syscall.CertChainPolicyStatus) (err error)
	RegOpenKeyEx(key syscall.Handle, subkey *uint16, options uint32, desiredAccess uint32, result *syscall.Handle) (regerrno error)
	RegCloseKey(key syscall.Handle) (regerrno error)
	RegQueryInfoKey(key syscall.Handle, class *uint16, classLen *uint32, reserved *uint32, subkeysLen *uint32, maxSubkeyLen *uint32, maxClassLen *uint32, valuesLen *uint32, maxValueNameLen *uint32, maxValueLen *uint32, saLen *uint32, lastWriteTime *syscall.Filetime) (regerrno error)
	RegEnumKeyEx(key syscall.Handle, index uint32, name *uint16, nameLen *uint32, reserved *uint32, class *uint16, classLen *uint32, lastWriteTime *syscall.Filetime) (regerrno error)
	RegQueryValueEx(key syscall.Handle, name *uint16, reserved *uint32, valtype *uint32, buf *byte, buflen *uint32) (regerrno error)
	GetConsoleMode(console syscall.Handle, mode *uint32) (err error)
	WriteConsole(console syscall.Handle, buf *uint16, towrite uint32, written *uint32, reserved *byte) (err error)
	ReadConsole(console syscall.Handle, buf *uint16, toread uint32, read *uint32, inputControl *byte) (err error)
	CreateToolhelp32Snapshot(flags uint32, processId uint32) (handle syscall.Handle, err error)
	Process32First(snapshot syscall.Handle, procEntry *syscall.ProcessEntry32) (err error)
	Process32Next(snapshot syscall.Handle, procEntry *syscall.ProcessEntry32) (err error)
	DeviceIoControl(handle syscall.Handle, ioControlCode uint32, inBuffer *byte, inBufferSize uint32, outBuffer *byte, outBufferSize uint32, bytesReturned *uint32, overlapped *syscall.Overlapped) (err error)
	CreateSymbolicLink(symlinkfilename *uint16, targetfilename *uint16, flags uint32) (err error)
	CreateHardLink(filename *uint16, existingfilename *uint16, reserved uintptr) (err error)
	WSAStartup(verreq uint32, data *syscall.WSAData) (sockerr error)
	WSACleanup() (err error)
	WSAIoctl(s syscall.Handle, iocc uint32, inbuf *byte, cbif uint32, outbuf *byte, cbob uint32, cbbr *uint32, overlapped *syscall.Overlapped, completionRoutine uintptr) (err error)
	Setsockopt(s syscall.Handle, level int32, optname int32, optval *byte, optlen int32) (err error)
	Getsockopt(s syscall.Handle, level int32, optname int32, optval *byte, optlen *int32) (err error)
	Closesocket(s syscall.Handle) (err error)
	AcceptEx(ls syscall.Handle, as syscall.Handle, buf *byte, rxdatalen uint32, laddrlen uint32, raddrlen uint32, recvd *uint32, overlapped *syscall.Overlapped) (err error)
	GetAcceptExSockaddrs(buf *byte, rxdatalen uint32, laddrlen uint32, raddrlen uint32, lrsa **syscall.RawSockaddrAny, lrsalen *int32, rrsa **syscall.RawSockaddrAny, rrsalen *int32)
	WSARecv(s syscall.Handle, bufs *syscall.WSABuf, bufcnt uint32, recvd *uint32, flags *uint32, overlapped *syscall.Overlapped, croutine *byte) (err error)
	WSASend(s syscall.Handle, bufs *syscall.WSABuf, bufcnt uint32, sent *uint32, flags uint32, overlapped *syscall.Overlapped, croutine *byte) (err error)
	WSARecvFrom(s syscall.Handle, bufs *syscall.WSABuf, bufcnt uint32, recvd *uint32, flags *uint32, from *syscall.RawSockaddrAny, fromlen *int32, overlapped *syscall.Overlapped, croutine *byte) (err error)
	WSASendTo(s syscall.Handle, bufs *syscall.WSABuf, bufcnt uint32, sent *uint32, flags uint32, to *syscall.RawSockaddrAny, tolen int32, overlapped *syscall.Overlapped, croutine *byte) (err error)
	GetHostByName(name string) (h *syscall.Hostent, err error)
	GetServByName(name string, proto string) (s *syscall.Servent, err error)
	Ntohs(netshort uint16) (u uint16)
	GetProtoByName(name string) (p *syscall.Protoent, err error)
	DnsQuery(name string, qtype uint16, options uint32, extra *byte, qrs **syscall.DNSRecord, pr *byte) (status error)
	DnsRecordListFree(rl *syscall.DNSRecord, freetype uint32)
	DnsNameCompare(name1 *uint16, name2 *uint16) (same bool)
	GetAddrInfoW(nodename *uint16, servicename *uint16, hints *syscall.AddrinfoW, result **syscall.AddrinfoW) (sockerr error)
	FreeAddrInfoW(addrinfo *syscall.AddrinfoW)
	GetIfEntry(pIfRow *syscall.MibIfRow) (errcode error)
	GetAdaptersInfo(ai *syscall.IpAdapterInfo, ol *uint32) (errcode error)
	SetFileCompletionNotificationModes(handle syscall.Handle, flags uint8) (err error)
	WSAEnumProtocols(protocols *int32, protocolBuffer *syscall.WSAProtocolInfo, bufferLength *uint32) (n int32, err error)
	TranslateName(accName *uint16, accNameFormat uint32, desiredNameFormat uint32, translatedName *uint16, nSize *uint32) (err error)
	GetUserNameEx(nameFormat uint32, nameBuffre *uint16, nSize *uint32) (err error)
	NetUserGetInfo(serverName *uint16, userName *uint16, level uint32, buf **byte) (neterr error)
	NetGetJoinInformation(server *uint16, name **uint16, bufType *uint32) (neterr error)
	NetApiBufferFree(buf *byte) (neterr error)
	LookupAccountSid(systemName *uint16, sid *syscall.SID, name *uint16, nameLen *uint32, refdDomainName *uint16, refdDomainNameLen *uint32, use *uint32) (err error)
	LookupAccountName(systemName *uint16, accountName *uint16, sid *syscall.SID, sidLen *uint32, refdDomainName *uint16, refdDomainNameLen *uint32, use *uint32) (err error)
	ConvertSidToStringSid(sid *syscall.SID, stringSid **uint16) (err error)
	ConvertStringSidToSid(stringSid *uint16, sid **syscall.SID) (err error)
	GetLengthSid(sid *syscall.SID) (len uint32)
	CopySid(destSidLen uint32, destSid *syscall.SID, srcSid *syscall.SID) (err error)
	OpenProcessToken(h syscall.Handle, access uint32, token *syscall.Token) (err error)
	GetTokenInformation(t syscall.Token, infoClass uint32, info *byte, infoLen uint32, returnedLen *uint32) (err error)
	GetUserProfileDirectory(t syscall.Token, dir *uint16, dirLen *uint32) (err error)
	NsecToFiletime(nsec int64) (ft syscall.Filetime)
}
