// This file was generated by counterfeiter
// with command: counterfeiter -p -o /Users/pivotal/workspace/nfs-volume-release/src/code.cloudfoundry.org/goshims/sqlshim database/sql
package sqlshim

import (
	"database/sql"
	"database/sql/driver"
)

//go:generate counterfeiter -o sql_fake/fake_sql.go . Sql
type Sql interface {
	Register(name string, driver driver.Driver)
	Drivers() []string
	Open(driverName, dataSourceName string) (*sql.DB, error)
}
