// This file was generated by counterfeiter
// with command: counterfeiter -p os/exec
// BUT THEN WE MODIFIED IT SO MAKE SURE TO COPY THOSE MODIFICATIONS FORWARDS
package execshim

import (
	"context"
	"os/exec"
)

type ExecShim struct{}

func (sh *ExecShim) Command(name string, arg ...string) Cmd {
	return exec.Command(name, arg...)
}

func (sh *ExecShim) CommandContext(ctx context.Context, name string, arg ...string) Cmd {
	return exec.CommandContext(ctx, name, arg...)
}

func (sh *ExecShim) LookPath(file string) (string, error) {
	return exec.LookPath(file)
}
