// This file was generated by counterfeiter
// with command: counterfeiter -p -o /Users/pivotal/workspace/local-volume-release/src/code.cloudfoundry.org/goshims/ioutilshim io/ioutil
// BUT THEN WE MODIFIED IT SO MAKE SURE TO COPY THOSE MODIFICATIONS FORWARDS
package ioutilshim

import (
	"io"
	"os"

	"code.cloudfoundry.org/goshims/osshim"
)

type IoutilShim struct{}

func (sh *IoutilShim) ReadAll(r io.Reader) ([]byte, error) {
	return io.ReadAll(r)
}

func (sh *IoutilShim) ReadFile(filename string) ([]byte, error) {
	return os.ReadFile(filename)
}

func (sh *IoutilShim) WriteFile(filename string, data []byte, perm os.FileMode) error {
	return os.WriteFile(filename, data, perm)
}

func (sh *IoutilShim) ReadDir(dirname string) ([]os.DirEntry, error) {
	return os.ReadDir(dirname)
}

func (sh *IoutilShim) NopCloser(r io.Reader) io.ReadCloser {
	return io.NopCloser(r)
}

func (sh *IoutilShim) TempFile(dir string, prefix string) (osshim.File, error) {
	f, err := os.CreateTemp(dir, prefix)
	return &osshim.FileShim{Delegate: f}, err
}

func (sh *IoutilShim) TempDir(dir string, prefix string) (name string, err error) {
	return os.MkdirTemp(dir, prefix)
}
